name: ccsd

services:

  backend:
    build: ./ccsd
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./ccsd/src:/app/src
    # environment:
    #   MONGO_URI: mongodb://root:Arman123@mongo:27017/
    networks:
      - mognonetwork
    depends_on:
      - mongo

  dashboard-js:
    build: ./dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dashboard/src:/app/src
    networks:
      - mognonetwork
    depends_on:
      - mongo
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mognonetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mognonetwork

networks:
  mognonetwork:
    driver: bridge

volumes:
  db_data:
